spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
project:
  poster: posters/

base:
  url: "http://localhost:8080"



