spring:
  datasource:
    username: postgres
    password: chill_101
    url: jdbc:postgresql://localhost:5432/movies
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: poster/

base:
  url: "http://localhost:8080"


